---
tags:
  - 技术/NET
---
## 举例

以一个示例展示异常处理机制的标准用法，以下是示例代码：

```C#
private void SomeMethod()
{
	try
	{
		// TODO: 需要得体的进行恢复或进行清理的代码
	}
	catch(InvalidOperationException)
	{
		// TODO: 从 InvalidOperationException 恢复的代码
	}
	catch(IOException)
	{
		// TODO: 从 IOException 恢复的代码
	}
	catch
	{
		// TODO: 从除了上述异常之外的其他所有异常恢复的代码。
		// ...
		// 如果所有异常都捕捉，通常需要重新抛出异常
		throw;
	}
	finally
	{
		// TODO: 对try块的任何操作进行清理
		// 这里的代码总是执行，无论是否抛出异常
	}
	// TODO: 未抛出异常，或某个catch块捕捉到异常，但没有抛出或重新抛出，就执行下面的代码
}
```

## try块

如果代码需要执行一般性的资源清理操作，需要从异常中恢复，或者两者都需要，就可以放到 try 块中。负责清理的代码应放到一个 finally 块中。try 块还可包含也许会抛出异常的代码。负责异常恢复的代码应放到一个或多个 catch 块中。针对应用程序能从中安全恢复的每一种异常，都应该创建一个 catch 块，一个 try 块至少得有一个管理的 catch 块或 finally 块。单独的 try 块没有意义也不被 C# 允许。

## catch 块

catch 块包含的是响应一个异常需要执行的代码。